apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: hpa-devopsng
  namespace: staging-devops
spec: 
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: deployment-devopsng
  minReplicas: 1
  maxReplicas: 3
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 560
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 220
