apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: model-scaledobject
  namespace: staging-locobuzz
  labels:
    deploymentName: deployment-modelbinder
spec:
  scaleTargetRef:
    name: deployment-modelbinder
  pollingInterval: 5
  cooldownPeriod:  60 # Default: 300 seconds
  minReplicaCount: 3
  maxReplicaCount: 20 # Max can go upto num of partitions you have in the topic
  triggers:
    - type: kafka
      metadata:
        consumerGroup: maprawdata-realtime-consumer-group
        bootstrapServers: b-1.locobuzzuatmskcluster.4psd4m.c3.kafka.ap-south-1.amazonaws.com:9092,b-2.locobuzzuatmskcluster.4psd4m.c3.kafka.ap-south-1.amazonaws.com:9092
        topic: RawStream_Realtime
        lagThreshold: "100"
        offsetResetPolicy: latest
