apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-{{ pipeline_name }}
  namespace: {{ namespace }}
  labels:
    app.type: "{{ app_type }}"
    product: "{{ product }}"
spec:
  # This template was edited via the frontend
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ pipeline_name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ pipeline_name }}
        app.type: "{{ app_type }}"
        service.name: "{{ pipeline_name }}"
        product: "{{ product }}"
    spec:
      serviceAccountName: {{ service_account }}
      containers:
      - name: {{ pipeline_name }}
        image: {{ image }}
        imagePullPolicy: Always
        ports:
          - containerPort: {{ target_port }}
        resources:
          limits:
            memory: "{{ memory_limit }}"
            cpu: "{{ cpu_limit }}"
          requests:
            memory: "{{ memory_request }}"
            cpu: "{{ cpu_request }}"
{{ node_affinity_section }}

---
apiVersion: v1
kind: Service
metadata:
  name: {{ pipeline_name }}
  namespace: {{ namespace }}
spec:
  selector:
    app.kubernetes.io/name: {{ pipeline_name }}
  ports:
    - protocol: TCP
      port: 80
      targetPort: {{ target_port }}
  type: {{ service_type }}